insert into walk_areas (id, name, is_active) values (1, 'Veith', true);
insert into walk_areas (id, name, is_active) values (2, 'Talmadge', true);
insert into walk_areas (id, name, is_active) values (3, 'Sage', true);
insert into walk_areas (id, name, is_active) values (4, 'Petterle', true);
insert into walk_areas (id, name, is_active) values (5, 'American', false);
insert into walk_areas (id, name, is_active) values (6, 'Ludington', true);
insert into walk_areas (id, name, is_active) values (7, 'Corscot', true);
insert into walk_areas (id, name, is_active) values (8, 'Redwing', true);
insert into walk_areas (id, name, is_active) values (9, 'Bayside', false);
insert into walk_areas (id, name, is_active) values (10, 'Mallory', false);
insert into walk_areas (id, name, is_active) values (11, 'Bashford', true);
insert into walk_areas (id, name, is_active) values (12, 'Sycamore', true);
insert into walk_areas (id, name, is_active) values (13, 'Bluestem', true);
insert into walk_areas (id, name, is_active) values (14, 'Pearson', true);
insert into walk_areas (id, name, is_active) values (15, 'Columbus', false);
insert into walk_areas (id, name, is_active) values (16, 'Service', true);
insert into walk_areas (id, name, is_active) values (17, 'Riverside', true);
insert into walk_areas (id, name, is_active) values (18, 'Carberry', true);
insert into walk_areas (id, name, is_active) values (19, 'Glacier Hill', true);
insert into walk_areas (id, name, is_active) values (20, 'Wayridge', true);
insert into walk_areas (id, name, is_active) values (21, 'Huxley', true);
insert into walk_areas (id, name, is_active) values (22, '3rd', true);
insert into walk_areas (id, name, is_active) values (23, 'Veith', true);
insert into walk_areas (id, name, is_active) values (24, 'Valley Edge', true);
insert into walk_areas (id, name, is_active) values (25, 'Kipling', false);
insert into walk_areas (id, name, is_active) values (26, 'Onsgard', true);
insert into walk_areas (id, name, is_active) values (27, 'Golden Leaf', false);
insert into walk_areas (id, name, is_active) values (28, 'Sherman', true);
insert into walk_areas (id, name, is_active) values (29, 'Londonderry', true);
insert into walk_areas (id, name, is_active) values (30, 'Victoria', true);
insert into walk_areas (id, name, is_active) values (31, 'Meadow Vale', false);
insert into walk_areas (id, name, is_active) values (32, 'Bunker Hill', true);
insert into walk_areas (id, name, is_active) values (33, 'Parkside', false);
insert into walk_areas (id, name, is_active) values (34, 'Fair Oaks', true);
insert into walk_areas (id, name, is_active) values (35, 'Redwing', true);
insert into walk_areas (id, name, is_active) values (36, 'Armistice', false);
insert into walk_areas (id, name, is_active) values (37, 'Becker', true);
insert into walk_areas (id, name, is_active) values (38, 'Paget', false);
insert into walk_areas (id, name, is_active) values (39, 'Sunnyside', true);
insert into walk_areas (id, name, is_active) values (40, 'Hagan', true);
insert into walk_areas (id, name, is_active) values (41, 'Springs', true);
insert into walk_areas (id, name, is_active) values (42, 'Dryden', true);
insert into walk_areas (id, name, is_active) values (43, 'Maple', true);
insert into walk_areas (id, name, is_active) values (44, 'Nancy', false);
insert into walk_areas (id, name, is_active) values (45, 'David', true);
insert into walk_areas (id, name, is_active) values (46, 'Eliot', true);
insert into walk_areas (id, name, is_active) values (47, 'Schlimgen', true);
insert into walk_areas (id, name, is_active) values (48, 'Lien', true);
insert into walk_areas (id, name, is_active) values (49, 'Annamark', true);
insert into walk_areas (id, name, is_active) values (50, 'Declaration', true);
insert into walk_areas (id, name, is_active) values (51, 'Ruskin', true);
insert into walk_areas (id, name, is_active) values (52, 'Bay', true);
insert into walk_areas (id, name, is_active) values (53, 'Hollow Ridge', true);
insert into walk_areas (id, name, is_active) values (54, 'Golf', true);
insert into walk_areas (id, name, is_active) values (55, 'Hansons', true);
insert into walk_areas (id, name, is_active) values (56, 'Evergreen', true);
insert into walk_areas (id, name, is_active) values (57, 'Atwood', false);
insert into walk_areas (id, name, is_active) values (58, 'Ridge Oak', true);
insert into walk_areas (id, name, is_active) values (59, 'Grayhawk', true);
insert into walk_areas (id, name, is_active) values (60, 'Pankratz', false);
insert into walk_areas (id, name, is_active) values (61, 'Pankratz', true);
insert into walk_areas (id, name, is_active) values (62, 'Pearson', true);
insert into walk_areas (id, name, is_active) values (63, 'Anniversary', true);
insert into walk_areas (id, name, is_active) values (64, 'Lakewood', true);
insert into walk_areas (id, name, is_active) values (65, 'Mayfield', true);
insert into walk_areas (id, name, is_active) values (66, 'Arapahoe', true);
insert into walk_areas (id, name, is_active) values (67, 'Farragut', true);
insert into walk_areas (id, name, is_active) values (68, 'Meadow Vale', false);
insert into walk_areas (id, name, is_active) values (69, 'Hintze', true);
insert into walk_areas (id, name, is_active) values (70, 'Rigney', true);
insert into walk_areas (id, name, is_active) values (71, 'Dunning', true);
insert into walk_areas (id, name, is_active) values (72, 'Oak Valley', true);
insert into walk_areas (id, name, is_active) values (73, 'Merchant', true);
insert into walk_areas (id, name, is_active) values (74, 'Warner', true);
insert into walk_areas (id, name, is_active) values (75, 'Paget', false);
insert into walk_areas (id, name, is_active) values (76, 'New Castle', true);
insert into walk_areas (id, name, is_active) values (77, 'Northwestern', true);
insert into walk_areas (id, name, is_active) values (78, 'Elgar', false);
insert into walk_areas (id, name, is_active) values (79, 'Messerschmidt', false);
insert into walk_areas (id, name, is_active) values (80, 'Granby', true);
insert into walk_areas (id, name, is_active) values (81, 'Daystar', true);
insert into walk_areas (id, name, is_active) values (82, 'Heath', true);
insert into walk_areas (id, name, is_active) values (83, 'American Ash', true);
insert into walk_areas (id, name, is_active) values (84, 'Bashford', true);
insert into walk_areas (id, name, is_active) values (85, 'Stone Corner', true);
insert into walk_areas (id, name, is_active) values (86, 'Towne', true);
insert into walk_areas (id, name, is_active) values (87, 'Bobwhite', true);
insert into walk_areas (id, name, is_active) values (88, 'Lakewood Gardens', true);
insert into walk_areas (id, name, is_active) values (89, 'Hagan', false);
insert into walk_areas (id, name, is_active) values (90, 'Judy', true);
insert into walk_areas (id, name, is_active) values (91, 'Oak Valley', true);
insert into walk_areas (id, name, is_active) values (92, 'Melvin', true);
insert into walk_areas (id, name, is_active) values (93, 'Division', false);
insert into walk_areas (id, name, is_active) values (94, 'Katie', true);
insert into walk_areas (id, name, is_active) values (95, 'Hooker', false);
insert into walk_areas (id, name, is_active) values (96, 'South', false);
insert into walk_areas (id, name, is_active) values (97, 'Elmside', true);
insert into walk_areas (id, name, is_active) values (98, 'Sunnyside', true);
insert into walk_areas (id, name, is_active) values (99, 'Jenifer', true);
insert into walk_areas (id, name, is_active) values (100, 'Cherokee', true);
insert into walk_areas (id, name, is_active) values (101, 'Comanche', false);
insert into walk_areas (id, name, is_active) values (102, 'Rigney', true);
insert into walk_areas (id, name, is_active) values (103, 'Dixon', true);
insert into walk_areas (id, name, is_active) values (104, '5th', true);
insert into walk_areas (id, name, is_active) values (105, 'Northwestern', true);
insert into walk_areas (id, name, is_active) values (106, 'Morning', true);
insert into walk_areas (id, name, is_active) values (107, 'Commercial', true);
insert into walk_areas (id, name, is_active) values (108, 'Petterle', false);
insert into walk_areas (id, name, is_active) values (109, 'Clyde Gallagher', false);
insert into walk_areas (id, name, is_active) values (110, 'Badeau', true);
insert into walk_areas (id, name, is_active) values (111, 'Waywood', true);
insert into walk_areas (id, name, is_active) values (112, 'Shoshone', false);
insert into walk_areas (id, name, is_active) values (113, 'Swallow', true);
insert into walk_areas (id, name, is_active) values (114, 'Manitowish', true);
insert into walk_areas (id, name, is_active) values (115, 'Talisman', true);
insert into walk_areas (id, name, is_active) values (116, 'Dakota', true);
insert into walk_areas (id, name, is_active) values (117, 'Cherokee', true);
insert into walk_areas (id, name, is_active) values (118, 'Walton', true);
insert into walk_areas (id, name, is_active) values (119, 'Pleasure', true);
insert into walk_areas (id, name, is_active) values (120, 'Stang', true);
insert into walk_areas (id, name, is_active) values (121, 'Pepper Wood', true);
insert into walk_areas (id, name, is_active) values (122, 'Meadow Valley', true);
insert into walk_areas (id, name, is_active) values (123, 'Autumn Leaf', true);
insert into walk_areas (id, name, is_active) values (124, 'American Ash', true);
insert into walk_areas (id, name, is_active) values (125, 'Loftsgordon', false);
insert into walk_areas (id, name, is_active) values (126, 'Pearson', false);
insert into walk_areas (id, name, is_active) values (127, 'Northwestern', true);
insert into walk_areas (id, name, is_active) values (128, 'Kennedy', false);
insert into walk_areas (id, name, is_active) values (129, 'Rutledge', true);
insert into walk_areas (id, name, is_active) values (130, 'Homewood', false);
insert into walk_areas (id, name, is_active) values (131, 'Bashford', true);
insert into walk_areas (id, name, is_active) values (132, 'Comanche', true);
insert into walk_areas (id, name, is_active) values (133, 'Bluestem', true);
insert into walk_areas (id, name, is_active) values (134, 'Commercial', true);
insert into walk_areas (id, name, is_active) values (135, 'Dottie', true);
insert into walk_areas (id, name, is_active) values (136, 'Northview', true);
insert into walk_areas (id, name, is_active) values (137, 'Bartillon', true);
insert into walk_areas (id, name, is_active) values (138, 'Green Ridge', false);
insert into walk_areas (id, name, is_active) values (139, 'Cody', true);
insert into walk_areas (id, name, is_active) values (140, 'Lillian', true);
insert into walk_areas (id, name, is_active) values (141, 'Kim', true);
insert into walk_areas (id, name, is_active) values (142, 'Butterfield', false);
insert into walk_areas (id, name, is_active) values (143, 'Amoth', true);
insert into walk_areas (id, name, is_active) values (144, 'Ronald Regan', true);
insert into walk_areas (id, name, is_active) values (145, 'High Crossing', true);
insert into walk_areas (id, name, is_active) values (146, 'Browning', false);
insert into walk_areas (id, name, is_active) values (147, 'Heath', false);
insert into walk_areas (id, name, is_active) values (148, 'Vera', false);
insert into walk_areas (id, name, is_active) values (149, 'Saint Paul', true);
insert into walk_areas (id, name, is_active) values (150, '8th', true);
insert into walk_areas (id, name, is_active) values (151, 'Helena', true);
insert into walk_areas (id, name, is_active) values (152, 'Lighthouse Bay', true);
insert into walk_areas (id, name, is_active) values (153, 'Stang', true);
insert into walk_areas (id, name, is_active) values (154, 'Sommers', true);
insert into walk_areas (id, name, is_active) values (155, 'Nancy', true);
insert into walk_areas (id, name, is_active) values (156, 'Mcguire', false);
insert into walk_areas (id, name, is_active) values (157, 'Badeau', true);
insert into walk_areas (id, name, is_active) values (158, 'Mallard', true);
insert into walk_areas (id, name, is_active) values (159, 'Brown', false);
insert into walk_areas (id, name, is_active) values (160, 'Red Cloud', true);
insert into walk_areas (id, name, is_active) values (161, 'Sheridan', true);
insert into walk_areas (id, name, is_active) values (162, 'Old Shore', true);
insert into walk_areas (id, name, is_active) values (163, 'Victoria', true);
insert into walk_areas (id, name, is_active) values (164, 'Debs', false);
insert into walk_areas (id, name, is_active) values (165, 'Karstens', true);
insert into walk_areas (id, name, is_active) values (166, 'Longview', true);
insert into walk_areas (id, name, is_active) values (167, 'Union', true);
insert into walk_areas (id, name, is_active) values (168, 'Golf', true);
insert into walk_areas (id, name, is_active) values (169, 'Lakewood', true);
insert into walk_areas (id, name, is_active) values (170, 'Autumn Leaf', false);
insert into walk_areas (id, name, is_active) values (171, 'Moland', true);
insert into walk_areas (id, name, is_active) values (172, 'Clarendon', true);
insert into walk_areas (id, name, is_active) values (173, 'Hagan', true);
insert into walk_areas (id, name, is_active) values (174, 'Park Meadow', true);
insert into walk_areas (id, name, is_active) values (175, 'Independence', true);
insert into walk_areas (id, name, is_active) values (176, 'Warrior', true);
insert into walk_areas (id, name, is_active) values (177, 'Bellgrove', true);
insert into walk_areas (id, name, is_active) values (178, 'Hazelcrest', true);
insert into walk_areas (id, name, is_active) values (179, 'Briar Crest', true);
insert into walk_areas (id, name, is_active) values (180, 'Claremont', true);
insert into walk_areas (id, name, is_active) values (181, 'Mayer', true);
insert into walk_areas (id, name, is_active) values (182, 'John Wall', false);
insert into walk_areas (id, name, is_active) values (183, 'Cordelia', false);
insert into walk_areas (id, name, is_active) values (184, 'Anthes', true);
insert into walk_areas (id, name, is_active) values (185, 'Shasta', true);
insert into walk_areas (id, name, is_active) values (186, 'Northwestern', false);
insert into walk_areas (id, name, is_active) values (187, 'Stone Corner', false);
insert into walk_areas (id, name, is_active) values (188, 'Arizona', true);
insert into walk_areas (id, name, is_active) values (189, 'Di Loreto', true);
insert into walk_areas (id, name, is_active) values (190, 'Amoth', true);
insert into walk_areas (id, name, is_active) values (191, 'Chive', true);
insert into walk_areas (id, name, is_active) values (192, 'Hayes', true);
insert into walk_areas (id, name, is_active) values (193, 'Lien', true);
insert into walk_areas (id, name, is_active) values (194, 'Bartillon', true);
insert into walk_areas (id, name, is_active) values (195, 'Thompson', true);
insert into walk_areas (id, name, is_active) values (196, 'Lakeland', true);
insert into walk_areas (id, name, is_active) values (197, 'Novick', false);
insert into walk_areas (id, name, is_active) values (198, 'Messerschmidt', true);
insert into walk_areas (id, name, is_active) values (199, 'Carey', false);
insert into walk_areas (id, name, is_active) values (200, 'Loeprich', true);
insert into walk_areas (id, name, is_active) values (201, 'Aberg', false);
insert into walk_areas (id, name, is_active) values (202, '8th', true);
insert into walk_areas (id, name, is_active) values (203, 'Graedel', false);
insert into walk_areas (id, name, is_active) values (204, 'Cordelia', true);
insert into walk_areas (id, name, is_active) values (205, 'Huxley', true);
insert into walk_areas (id, name, is_active) values (206, 'Talisman', true);
insert into walk_areas (id, name, is_active) values (207, 'Morning', true);
insert into walk_areas (id, name, is_active) values (208, 'Tennyson', true);
insert into walk_areas (id, name, is_active) values (209, 'Daystar', true);
insert into walk_areas (id, name, is_active) values (210, 'Anzinger', true);
insert into walk_areas (id, name, is_active) values (211, 'Harper', true);
insert into walk_areas (id, name, is_active) values (212, 'Reinke', false);
insert into walk_areas (id, name, is_active) values (213, 'Schiller', true);
insert into walk_areas (id, name, is_active) values (214, 'Kropf', true);
insert into walk_areas (id, name, is_active) values (215, 'Manufacturers', true);
insert into walk_areas (id, name, is_active) values (216, 'Mesta', false);
insert into walk_areas (id, name, is_active) values (217, 'Vernon', false);
insert into walk_areas (id, name, is_active) values (218, 'Pankratz', false);
insert into walk_areas (id, name, is_active) values (219, 'Clove', true);
insert into walk_areas (id, name, is_active) values (220, 'Pleasure', true);
insert into walk_areas (id, name, is_active) values (221, '3rd', true);
insert into walk_areas (id, name, is_active) values (222, 'Starling', true);
insert into walk_areas (id, name, is_active) values (223, 'Shasta', true);
insert into walk_areas (id, name, is_active) values (224, 'Eagan', true);
insert into walk_areas (id, name, is_active) values (225, 'Packers', true);
insert into walk_areas (id, name, is_active) values (226, 'Derek', true);
insert into walk_areas (id, name, is_active) values (227, 'Sheridan', true);
insert into walk_areas (id, name, is_active) values (228, 'Crest Line', true);
insert into walk_areas (id, name, is_active) values (229, 'Northland', true);
insert into walk_areas (id, name, is_active) values (230, 'Fairview', false);
insert into walk_areas (id, name, is_active) values (231, 'Walton', true);
insert into walk_areas (id, name, is_active) values (232, 'Muir', true);
insert into walk_areas (id, name, is_active) values (233, 'Old Shore', true);
insert into walk_areas (id, name, is_active) values (234, 'Maryland', true);
insert into walk_areas (id, name, is_active) values (235, 'Fallview', true);
insert into walk_areas (id, name, is_active) values (236, 'Hermina', true);
insert into walk_areas (id, name, is_active) values (237, 'Talmadge', true);
insert into walk_areas (id, name, is_active) values (238, 'Riverside', true);
insert into walk_areas (id, name, is_active) values (239, 'Hanson', true);
insert into walk_areas (id, name, is_active) values (240, 'Lakewood Gardens', false);
insert into walk_areas (id, name, is_active) values (241, 'East', true);
insert into walk_areas (id, name, is_active) values (242, 'Anthes', true);
insert into walk_areas (id, name, is_active) values (243, 'Westridge', true);
insert into walk_areas (id, name, is_active) values (244, 'David', true);
insert into walk_areas (id, name, is_active) values (245, 'Northwestern', true);
insert into walk_areas (id, name, is_active) values (246, 'Leroy', true);
insert into walk_areas (id, name, is_active) values (247, 'Anhalt', true);
insert into walk_areas (id, name, is_active) values (248, 'Hooker', true);
insert into walk_areas (id, name, is_active) values (249, 'Westridge', true);
insert into walk_areas (id, name, is_active) values (250, 'Rockefeller', true);
insert into walk_areas (id, name, is_active) values (251, 'Melvin', false);
insert into walk_areas (id, name, is_active) values (252, 'Wayridge', true);
insert into walk_areas (id, name, is_active) values (253, 'South', false);
insert into walk_areas (id, name, is_active) values (254, 'Russell', true);
insert into walk_areas (id, name, is_active) values (255, 'Bartelt', true);
insert into walk_areas (id, name, is_active) values (256, 'Judy', true);
insert into walk_areas (id, name, is_active) values (257, 'John Wall', true);
insert into walk_areas (id, name, is_active) values (258, 'Warner', true);
insert into walk_areas (id, name, is_active) values (259, 'Gerald', false);
insert into walk_areas (id, name, is_active) values (260, 'Elmside', true);
insert into walk_areas (id, name, is_active) values (261, 'Sheridan', true);
insert into walk_areas (id, name, is_active) values (262, 'Granby', true);
insert into walk_areas (id, name, is_active) values (263, 'Grasskamp', true);
insert into walk_areas (id, name, is_active) values (264, 'Red Cloud', true);
insert into walk_areas (id, name, is_active) values (265, 'Golden Leaf', true);
insert into walk_areas (id, name, is_active) values (266, 'Buena Vista', true);
insert into walk_areas (id, name, is_active) values (267, 'Butternut', true);
insert into walk_areas (id, name, is_active) values (268, 'Roth', true);
insert into walk_areas (id, name, is_active) values (269, 'Warner', true);
insert into walk_areas (id, name, is_active) values (270, 'Dapin', true);
insert into walk_areas (id, name, is_active) values (271, 'Maple Wood', true);
insert into walk_areas (id, name, is_active) values (272, 'Eagan', false);
insert into walk_areas (id, name, is_active) values (273, 'Hoffman', true);
insert into walk_areas (id, name, is_active) values (274, 'Monterey', true);
insert into walk_areas (id, name, is_active) values (275, 'Lakewood', true);
insert into walk_areas (id, name, is_active) values (276, 'Becker', true);
insert into walk_areas (id, name, is_active) values (277, 'Mcguire', false);
insert into walk_areas (id, name, is_active) values (278, 'Haas', true);
insert into walk_areas (id, name, is_active) values (279, 'Knutson', true);
insert into walk_areas (id, name, is_active) values (280, 'La Follette', true);
insert into walk_areas (id, name, is_active) values (281, 'Algoma', true);
insert into walk_areas (id, name, is_active) values (282, 'Barnett', true);
insert into walk_areas (id, name, is_active) values (283, 'Ramsey', true);
insert into walk_areas (id, name, is_active) values (284, 'Algoma', false);
insert into walk_areas (id, name, is_active) values (285, 'Gulseth', false);
insert into walk_areas (id, name, is_active) values (286, 'Springs', true);
insert into walk_areas (id, name, is_active) values (287, 'Bluejay', true);
insert into walk_areas (id, name, is_active) values (288, 'Holmberg', true);
insert into walk_areas (id, name, is_active) values (289, 'Melby', false);
insert into walk_areas (id, name, is_active) values (290, 'Mallory', true);
insert into walk_areas (id, name, is_active) values (291, 'Pankratz', true);
insert into walk_areas (id, name, is_active) values (292, 'Thompson', true);
insert into walk_areas (id, name, is_active) values (293, '6th', false);
insert into walk_areas (id, name, is_active) values (294, 'Anniversary', true);
insert into walk_areas (id, name, is_active) values (295, 'Pleasure', true);
insert into walk_areas (id, name, is_active) values (296, 'Cottonwood', true);
insert into walk_areas (id, name, is_active) values (297, 'Haas', true);
insert into walk_areas (id, name, is_active) values (298, 'Lukken', true);
insert into walk_areas (id, name, is_active) values (299, 'Bunting', true);
insert into walk_areas (id, name, is_active) values (300, 'Dorton', true);
insert into walk_areas (id, name, is_active) values (301, 'Hauk', false);
insert into walk_areas (id, name, is_active) values (302, 'Doe Crossing', false);
insert into walk_areas (id, name, is_active) values (303, 'Alpine', true);
insert into walk_areas (id, name, is_active) values (304, 'Dayton', true);
insert into walk_areas (id, name, is_active) values (305, 'Harbort', true);
insert into walk_areas (id, name, is_active) values (306, 'Kedzie', true);
insert into walk_areas (id, name, is_active) values (307, 'Gerald', true);
insert into walk_areas (id, name, is_active) values (308, 'Randy', false);
insert into walk_areas (id, name, is_active) values (309, 'Clove', true);
insert into walk_areas (id, name, is_active) values (310, 'Shelley', false);
insert into walk_areas (id, name, is_active) values (311, 'Eastwood', true);
insert into walk_areas (id, name, is_active) values (312, 'Rockefeller', true);
insert into walk_areas (id, name, is_active) values (313, 'Dovetail', true);
insert into walk_areas (id, name, is_active) values (314, 'Di Loreto', true);
insert into walk_areas (id, name, is_active) values (315, 'Elka', true);
insert into walk_areas (id, name, is_active) values (316, 'Starling', true);
insert into walk_areas (id, name, is_active) values (317, 'Vermont', false);
insert into walk_areas (id, name, is_active) values (318, 'Longview', true);
insert into walk_areas (id, name, is_active) values (319, 'Northland', false);
insert into walk_areas (id, name, is_active) values (320, 'Bunting', true);
insert into walk_areas (id, name, is_active) values (321, 'Moose', true);
insert into walk_areas (id, name, is_active) values (322, 'Miller', true);
insert into walk_areas (id, name, is_active) values (323, 'Eliot', true);
insert into walk_areas (id, name, is_active) values (324, 'Twin Pines', true);
insert into walk_areas (id, name, is_active) values (325, 'Petterle', true);
insert into walk_areas (id, name, is_active) values (326, 'Hooker', true);
insert into walk_areas (id, name, is_active) values (327, 'Canary', true);
insert into walk_areas (id, name, is_active) values (328, 'Luster', true);
insert into walk_areas (id, name, is_active) values (329, 'Kensington', true);
insert into walk_areas (id, name, is_active) values (330, 'Warbler', true);
insert into walk_areas (id, name, is_active) values (331, 'Morningstar', true);
insert into walk_areas (id, name, is_active) values (332, 'Del Sol', true);
insert into walk_areas (id, name, is_active) values (333, 'Amoth', true);
insert into walk_areas (id, name, is_active) values (334, 'Bultman', false);
insert into walk_areas (id, name, is_active) values (335, 'Rieder', false);
insert into walk_areas (id, name, is_active) values (336, 'Debra', false);
insert into walk_areas (id, name, is_active) values (337, 'Donald', true);
insert into walk_areas (id, name, is_active) values (338, 'Packers', true);
insert into walk_areas (id, name, is_active) values (339, 'Merrick', true);
insert into walk_areas (id, name, is_active) values (340, 'Thackeray', true);
insert into walk_areas (id, name, is_active) values (341, 'Green', false);
insert into walk_areas (id, name, is_active) values (342, 'Brown', true);
insert into walk_areas (id, name, is_active) values (343, 'Luster', true);
insert into walk_areas (id, name, is_active) values (344, 'Elgar', false);
insert into walk_areas (id, name, is_active) values (345, 'Luster', true);
insert into walk_areas (id, name, is_active) values (346, 'Cascade', true);
insert into walk_areas (id, name, is_active) values (347, 'Morning', true);
insert into walk_areas (id, name, is_active) values (348, 'Eastwood', false);
insert into walk_areas (id, name, is_active) values (349, 'Moose', true);
insert into walk_areas (id, name, is_active) values (350, 'Prairieview', true);
insert into walk_areas (id, name, is_active) values (351, 'Chive', true);
insert into walk_areas (id, name, is_active) values (352, 'Riverside', true);
insert into walk_areas (id, name, is_active) values (353, 'Manitowish', true);
insert into walk_areas (id, name, is_active) values (354, 'Brentwood', true);
insert into walk_areas (id, name, is_active) values (355, 'Carioca', true);
insert into walk_areas (id, name, is_active) values (356, 'Grasskamp', true);
insert into walk_areas (id, name, is_active) values (357, 'Eggendart', false);
insert into walk_areas (id, name, is_active) values (358, 'Fairview', false);
insert into walk_areas (id, name, is_active) values (359, 'Dayton', false);
insert into walk_areas (id, name, is_active) values (360, 'Melvin', true);
insert into walk_areas (id, name, is_active) values (361, 'Summer Ridge', true);
insert into walk_areas (id, name, is_active) values (362, 'Kingsford', true);
insert into walk_areas (id, name, is_active) values (363, 'Lien', true);
insert into walk_areas (id, name, is_active) values (364, 'Dayton', false);
insert into walk_areas (id, name, is_active) values (365, 'Hoard', true);
insert into walk_areas (id, name, is_active) values (366, 'Portage', false);
insert into walk_areas (id, name, is_active) values (367, 'Brentwood', true);
insert into walk_areas (id, name, is_active) values (368, 'Transport', true);
insert into walk_areas (id, name, is_active) values (369, 'Luster', true);
insert into walk_areas (id, name, is_active) values (370, 'Mayer', true);
insert into walk_areas (id, name, is_active) values (371, 'Magdeline', false);
insert into walk_areas (id, name, is_active) values (372, 'Shelley', true);
insert into walk_areas (id, name, is_active) values (373, 'Hollow Ridge', true);
insert into walk_areas (id, name, is_active) values (374, 'Bellgrove', false);
insert into walk_areas (id, name, is_active) values (375, 'Homewood', true);
insert into walk_areas (id, name, is_active) values (376, 'Jay', true);
insert into walk_areas (id, name, is_active) values (377, 'Emmet', false);
insert into walk_areas (id, name, is_active) values (378, 'Northview', true);
insert into walk_areas (id, name, is_active) values (379, 'Old Gate', true);
insert into walk_areas (id, name, is_active) values (380, 'Meadow Vale', true);
insert into walk_areas (id, name, is_active) values (381, 'Division', true);
insert into walk_areas (id, name, is_active) values (382, 'Atwood', true);
insert into walk_areas (id, name, is_active) values (383, 'Leroy', true);
insert into walk_areas (id, name, is_active) values (384, 'Florence', true);
insert into walk_areas (id, name, is_active) values (385, 'Marcy', true);
insert into walk_areas (id, name, is_active) values (386, 'David', false);
insert into walk_areas (id, name, is_active) values (387, 'Fallview', true);
insert into walk_areas (id, name, is_active) values (388, 'John Wall', true);
insert into walk_areas (id, name, is_active) values (389, 'Sachtjen', true);
insert into walk_areas (id, name, is_active) values (390, 'Forster', true);
insert into walk_areas (id, name, is_active) values (391, 'Sloan', true);
insert into walk_areas (id, name, is_active) values (392, 'Mitchell', true);
insert into walk_areas (id, name, is_active) values (393, 'Lighthouse Bay', true);
insert into walk_areas (id, name, is_active) values (394, 'Barnett', true);
insert into walk_areas (id, name, is_active) values (395, 'Harbort', true);
insert into walk_areas (id, name, is_active) values (396, 'Bonner', true);
insert into walk_areas (id, name, is_active) values (397, '2nd', true);
insert into walk_areas (id, name, is_active) values (398, 'Melrose', true);
insert into walk_areas (id, name, is_active) values (399, 'Lindbergh', false);
insert into walk_areas (id, name, is_active) values (400, 'Chive', true);
insert into walk_areas (id, name, is_active) values (401, 'Eliot', true);
insert into walk_areas (id, name, is_active) values (402, 'Garrison', false);
insert into walk_areas (id, name, is_active) values (403, 'Kropf', true);
insert into walk_areas (id, name, is_active) values (404, 'Algoma', true);
insert into walk_areas (id, name, is_active) values (405, 'Mccormick', true);
insert into walk_areas (id, name, is_active) values (406, 'Hoepker', true);
insert into walk_areas (id, name, is_active) values (407, 'Beilfuss', true);
insert into walk_areas (id, name, is_active) values (408, 'Bayside', true);
insert into walk_areas (id, name, is_active) values (409, 'Eggendart', true);
insert into walk_areas (id, name, is_active) values (410, 'Glendale', true);
insert into walk_areas (id, name, is_active) values (411, 'Nancy', false);
insert into walk_areas (id, name, is_active) values (412, 'Birchwood', true);
insert into walk_areas (id, name, is_active) values (413, 'Stone Corner', true);
insert into walk_areas (id, name, is_active) values (414, 'Moland', true);
insert into walk_areas (id, name, is_active) values (415, 'Iowa', true);
insert into walk_areas (id, name, is_active) values (416, 'Center', true);
insert into walk_areas (id, name, is_active) values (417, 'Sachtjen', false);
insert into walk_areas (id, name, is_active) values (418, 'School', true);
insert into walk_areas (id, name, is_active) values (419, 'Fairfield', true);
insert into walk_areas (id, name, is_active) values (420, 'Melrose', true);
insert into walk_areas (id, name, is_active) values (421, 'Schurz', false);
insert into walk_areas (id, name, is_active) values (422, 'Shoshone', true);
insert into walk_areas (id, name, is_active) values (423, 'Arrowood', true);
insert into walk_areas (id, name, is_active) values (424, 'Shasta', true);
insert into walk_areas (id, name, is_active) values (425, 'Canary', true);
insert into walk_areas (id, name, is_active) values (426, 'Hagan', true);
insert into walk_areas (id, name, is_active) values (427, 'Loomis', true);
insert into walk_areas (id, name, is_active) values (428, 'Packers', true);
insert into walk_areas (id, name, is_active) values (429, 'Oxford', true);
insert into walk_areas (id, name, is_active) values (430, 'Jackson', true);
insert into walk_areas (id, name, is_active) values (431, 'Kinsman', true);
insert into walk_areas (id, name, is_active) values (432, 'Debs', true);
insert into walk_areas (id, name, is_active) values (433, 'Fuller', true);
insert into walk_areas (id, name, is_active) values (434, 'Washington', true);
insert into walk_areas (id, name, is_active) values (435, 'Lakeland', true);
insert into walk_areas (id, name, is_active) values (436, 'Main', true);
insert into walk_areas (id, name, is_active) values (437, 'Ryan', true);
insert into walk_areas (id, name, is_active) values (438, 'Jana', true);
insert into walk_areas (id, name, is_active) values (439, 'Clemons', true);
insert into walk_areas (id, name, is_active) values (440, 'Raven', true);
insert into walk_areas (id, name, is_active) values (441, 'Old Shore', true);
insert into walk_areas (id, name, is_active) values (442, 'Mesta', true);
insert into walk_areas (id, name, is_active) values (443, 'Acker', true);
insert into walk_areas (id, name, is_active) values (444, 'Clarendon', true);
insert into walk_areas (id, name, is_active) values (445, 'Mariners Cove', true);
insert into walk_areas (id, name, is_active) values (446, 'Hoard', false);
insert into walk_areas (id, name, is_active) values (447, 'Hansons', true);
insert into walk_areas (id, name, is_active) values (448, 'Dovetail', true);
insert into walk_areas (id, name, is_active) values (449, 'Jenna', true);
insert into walk_areas (id, name, is_active) values (450, 'Fallview', true);
insert into walk_areas (id, name, is_active) values (451, 'Holmberg', true);
insert into walk_areas (id, name, is_active) values (452, 'Valley Edge', true);
insert into walk_areas (id, name, is_active) values (453, 'Sherman', true);
insert into walk_areas (id, name, is_active) values (454, '1st', true);
insert into walk_areas (id, name, is_active) values (455, 'Little Fleur', false);
insert into walk_areas (id, name, is_active) values (456, 'Johnson', true);
insert into walk_areas (id, name, is_active) values (457, 'Scoville', true);
insert into walk_areas (id, name, is_active) values (458, 'Bartelt', true);
insert into walk_areas (id, name, is_active) values (459, 'Sutteridge', true);
insert into walk_areas (id, name, is_active) values (460, 'Almo', true);
insert into walk_areas (id, name, is_active) values (461, 'Glendale', true);
insert into walk_areas (id, name, is_active) values (462, 'Johnson', true);
insert into walk_areas (id, name, is_active) values (463, 'Hermina', true);
insert into walk_areas (id, name, is_active) values (464, 'Haas', true);
insert into walk_areas (id, name, is_active) values (465, 'Longview', true);
insert into walk_areas (id, name, is_active) values (466, 'Melrose', false);
insert into walk_areas (id, name, is_active) values (467, 'Kensington', true);
insert into walk_areas (id, name, is_active) values (468, 'Sachtjen', true);
insert into walk_areas (id, name, is_active) values (469, 'Old Gate', false);
insert into walk_areas (id, name, is_active) values (470, 'Kensington', true);
insert into walk_areas (id, name, is_active) values (471, 'Center', true);
insert into walk_areas (id, name, is_active) values (472, 'Londonderry', false);
insert into walk_areas (id, name, is_active) values (473, '5th', true);
insert into walk_areas (id, name, is_active) values (474, 'Briar Crest', true);
insert into walk_areas (id, name, is_active) values (475, 'Kedzie', true);
insert into walk_areas (id, name, is_active) values (476, 'Butternut', false);
insert into walk_areas (id, name, is_active) values (477, 'Kings', true);
insert into walk_areas (id, name, is_active) values (478, 'Briar Crest', false);
insert into walk_areas (id, name, is_active) values (479, 'Red Cloud', true);
insert into walk_areas (id, name, is_active) values (480, 'Harbort', false);
insert into walk_areas (id, name, is_active) values (481, 'Helena', true);
insert into walk_areas (id, name, is_active) values (482, 'Lawn', true);
insert into walk_areas (id, name, is_active) values (483, 'Thompson', true);
insert into walk_areas (id, name, is_active) values (484, 'Claremont', true);
insert into walk_areas (id, name, is_active) values (485, 'Straubel', true);
insert into walk_areas (id, name, is_active) values (486, 'Ramsey', false);
insert into walk_areas (id, name, is_active) values (487, 'Farwell', false);
insert into walk_areas (id, name, is_active) values (488, 'Esker', false);
insert into walk_areas (id, name, is_active) values (489, 'West', false);
insert into walk_areas (id, name, is_active) values (490, 'Boyd', true);
insert into walk_areas (id, name, is_active) values (491, 'Hauk', true);
insert into walk_areas (id, name, is_active) values (492, 'Schmedeman', true);
insert into walk_areas (id, name, is_active) values (493, 'International', true);
insert into walk_areas (id, name, is_active) values (494, 'Coleman', true);
insert into walk_areas (id, name, is_active) values (495, 'Debra', true);
insert into walk_areas (id, name, is_active) values (496, 'South', false);
insert into walk_areas (id, name, is_active) values (497, 'Lyons', true);
insert into walk_areas (id, name, is_active) values (498, 'Northport', true);
insert into walk_areas (id, name, is_active) values (499, 'Glacier Hill', true);
insert into walk_areas (id, name, is_active) values (500, 'Stuart', true);
insert into walk_areas (id, name, is_active) values (501, 'Ohio', true);
insert into walk_areas (id, name, is_active) values (502, 'Milwaukee', true);
insert into walk_areas (id, name, is_active) values (503, 'Magdeline', true);
insert into walk_areas (id, name, is_active) values (504, 'Bultman', true);
insert into walk_areas (id, name, is_active) values (505, 'Dunning', false);
insert into walk_areas (id, name, is_active) values (506, 'Saint Paul', true);
insert into walk_areas (id, name, is_active) values (507, 'Manley', false);
insert into walk_areas (id, name, is_active) values (508, 'Tony', true);
insert into walk_areas (id, name, is_active) values (509, 'Moose', true);
insert into walk_areas (id, name, is_active) values (510, 'Lakewood Gardens', true);
insert into walk_areas (id, name, is_active) values (511, 'Everett', true);
insert into walk_areas (id, name, is_active) values (512, 'Bartelt', true);
insert into walk_areas (id, name, is_active) values (513, 'Golden Leaf', true);
insert into walk_areas (id, name, is_active) values (514, 'Sunbrook', true);
insert into walk_areas (id, name, is_active) values (515, 'Little Fleur', true);
insert into walk_areas (id, name, is_active) values (516, 'Buell', true);
insert into walk_areas (id, name, is_active) values (517, 'Northview', true);
insert into walk_areas (id, name, is_active) values (518, 'Delladonna', true);
insert into walk_areas (id, name, is_active) values (519, 'Glacier Hill', false);
insert into walk_areas (id, name, is_active) values (520, 'Roxbury', true);
insert into walk_areas (id, name, is_active) values (521, 'Hanover', false);
insert into walk_areas (id, name, is_active) values (522, 'Claremont', false);
insert into walk_areas (id, name, is_active) values (523, 'Eastlawn', true);
insert into walk_areas (id, name, is_active) values (524, 'Jenna', true);
insert into walk_areas (id, name, is_active) values (525, 'Superior', true);
insert into walk_areas (id, name, is_active) values (526, 'Raven', true);
insert into walk_areas (id, name, is_active) values (527, 'Montana', false);
insert into walk_areas (id, name, is_active) values (528, 'Hermina', true);
insert into walk_areas (id, name, is_active) values (529, 'Forest', true);
insert into walk_areas (id, name, is_active) values (530, 'Little Fleur', false);
insert into walk_areas (id, name, is_active) values (531, 'Helena', true);
insert into walk_areas (id, name, is_active) values (532, 'Lien', true);
insert into walk_areas (id, name, is_active) values (533, 'Merry', true);
insert into walk_areas (id, name, is_active) values (534, 'Buena Vista', true);
insert into walk_areas (id, name, is_active) values (535, 'Karstens', true);
insert into walk_areas (id, name, is_active) values (536, 'Everett', true);
insert into walk_areas (id, name, is_active) values (537, 'Forster', true);
insert into walk_areas (id, name, is_active) values (538, 'Golf Course', true);
insert into walk_areas (id, name, is_active) values (539, 'Sycamore', true);
insert into walk_areas (id, name, is_active) values (540, 'Schmedeman', false);
insert into walk_areas (id, name, is_active) values (541, 'Melvin', true);
insert into walk_areas (id, name, is_active) values (542, 'Hovde', true);
insert into walk_areas (id, name, is_active) values (543, '8th', true);
insert into walk_areas (id, name, is_active) values (544, 'Stoughton', true);
insert into walk_areas (id, name, is_active) values (545, 'Southridge', true);
insert into walk_areas (id, name, is_active) values (546, 'Grover', true);
insert into walk_areas (id, name, is_active) values (547, 'Bonner', true);
insert into walk_areas (id, name, is_active) values (548, 'Arapahoe', true);
insert into walk_areas (id, name, is_active) values (549, 'Manitowish', true);
insert into walk_areas (id, name, is_active) values (550, 'Veith', true);
insert into walk_areas (id, name, is_active) values (551, 'Kings', true);
insert into walk_areas (id, name, is_active) values (552, 'Porter', true);
insert into walk_areas (id, name, is_active) values (553, 'Eagan', false);
insert into walk_areas (id, name, is_active) values (554, 'Superior', true);
insert into walk_areas (id, name, is_active) values (555, 'Portage', false);
insert into walk_areas (id, name, is_active) values (556, 'Swallow', false);
insert into walk_areas (id, name, is_active) values (557, 'Havey', true);
insert into walk_areas (id, name, is_active) values (558, 'Roxbury', true);
insert into walk_areas (id, name, is_active) values (559, 'Acker', true);
insert into walk_areas (id, name, is_active) values (560, 'Redwing', true);
insert into walk_areas (id, name, is_active) values (561, 'Anzinger', true);
insert into walk_areas (id, name, is_active) values (562, 'North', false);
insert into walk_areas (id, name, is_active) values (563, 'Maple Wood', false);
insert into walk_areas (id, name, is_active) values (564, 'Lindbergh', true);
insert into walk_areas (id, name, is_active) values (565, 'Vera', false);
insert into walk_areas (id, name, is_active) values (566, 'Sloan', true);
insert into walk_areas (id, name, is_active) values (567, 'Evergreen', true);
insert into walk_areas (id, name, is_active) values (568, 'Claremont', true);
insert into walk_areas (id, name, is_active) values (569, 'Moose', true);
insert into walk_areas (id, name, is_active) values (570, 'Lotheville', false);
insert into walk_areas (id, name, is_active) values (571, 'Merchant', true);
insert into walk_areas (id, name, is_active) values (572, 'Darwin', true);
insert into walk_areas (id, name, is_active) values (573, 'Morning', true);
insert into walk_areas (id, name, is_active) values (574, 'Elgar', false);
insert into walk_areas (id, name, is_active) values (575, 'Gina', true);
insert into walk_areas (id, name, is_active) values (576, 'Mariners Cove', true);
insert into walk_areas (id, name, is_active) values (577, 'Hovde', true);
insert into walk_areas (id, name, is_active) values (578, 'High Crossing', false);
insert into walk_areas (id, name, is_active) values (579, 'Mifflin', true);
insert into walk_areas (id, name, is_active) values (580, 'Moulton', true);
insert into walk_areas (id, name, is_active) values (581, 'Blackbird', true);
insert into walk_areas (id, name, is_active) values (582, 'Sage', true);
insert into walk_areas (id, name, is_active) values (583, 'Merry', false);
insert into walk_areas (id, name, is_active) values (584, 'Florence', true);
insert into walk_areas (id, name, is_active) values (585, 'Jackson', true);
insert into walk_areas (id, name, is_active) values (586, 'Leroy', false);
insert into walk_areas (id, name, is_active) values (587, 'Myrtle', true);
insert into walk_areas (id, name, is_active) values (588, 'Continental', false);
insert into walk_areas (id, name, is_active) values (589, 'Blackbird', true);
insert into walk_areas (id, name, is_active) values (590, 'Saint Paul', false);
insert into walk_areas (id, name, is_active) values (591, 'Russell', true);
insert into walk_areas (id, name, is_active) values (592, 'Valley Edge', false);
insert into walk_areas (id, name, is_active) values (593, 'Lotheville', true);
insert into walk_areas (id, name, is_active) values (594, 'Lyons', false);
insert into walk_areas (id, name, is_active) values (595, 'Onsgard', true);
insert into walk_areas (id, name, is_active) values (596, 'Division', true);
insert into walk_areas (id, name, is_active) values (597, 'Jackson', true);
insert into walk_areas (id, name, is_active) values (598, 'Ruskin', true);
insert into walk_areas (id, name, is_active) values (599, '6th', true);
insert into walk_areas (id, name, is_active) values (600, 'Mayer', false);
insert into walk_areas (id, name, is_active) values (601, 'Twin Pines', true);
insert into walk_areas (id, name, is_active) values (602, 'Valley Edge', false);
insert into walk_areas (id, name, is_active) values (603, 'Green Ridge', true);
insert into walk_areas (id, name, is_active) values (604, 'Carpenter', true);
insert into walk_areas (id, name, is_active) values (605, 'Westport', true);
insert into walk_areas (id, name, is_active) values (606, 'Messerschmidt', false);
insert into walk_areas (id, name, is_active) values (607, 'Bunker Hill', true);
insert into walk_areas (id, name, is_active) values (608, 'Eastwood', true);
insert into walk_areas (id, name, is_active) values (609, 'Golden Leaf', true);
insert into walk_areas (id, name, is_active) values (610, 'Schlimgen', true);
insert into walk_areas (id, name, is_active) values (611, 'Straubel', false);
insert into walk_areas (id, name, is_active) values (612, 'Del Sol', true);
insert into walk_areas (id, name, is_active) values (613, 'Daystar', true);
insert into walk_areas (id, name, is_active) values (614, 'Susan', true);
insert into walk_areas (id, name, is_active) values (615, 'Anzinger', true);
insert into walk_areas (id, name, is_active) values (616, 'Laurel', true);
insert into walk_areas (id, name, is_active) values (617, 'Golf', true);
insert into walk_areas (id, name, is_active) values (618, 'Melrose', true);
insert into walk_areas (id, name, is_active) values (619, 'Sachtjen', true);
insert into walk_areas (id, name, is_active) values (620, 'Springs', true);
insert into walk_areas (id, name, is_active) values (621, 'Lindbergh', false);
insert into walk_areas (id, name, is_active) values (622, 'Everett', true);
insert into walk_areas (id, name, is_active) values (623, 'Waxwing', true);
insert into walk_areas (id, name, is_active) values (624, 'Fallview', true);
insert into walk_areas (id, name, is_active) values (625, 'Meadow Valley', true);
insert into walk_areas (id, name, is_active) values (626, 'Hoepker', true);
insert into walk_areas (id, name, is_active) values (627, 'Ridgeview', true);
insert into walk_areas (id, name, is_active) values (628, 'Dwight', true);
insert into walk_areas (id, name, is_active) values (629, 'School', true);
insert into walk_areas (id, name, is_active) values (630, 'Eastwood', true);
insert into walk_areas (id, name, is_active) values (631, 'Northland', true);
insert into walk_areas (id, name, is_active) values (632, 'Boyd', true);
insert into walk_areas (id, name, is_active) values (633, 'Onsgard', true);
insert into walk_areas (id, name, is_active) values (634, 'Mayer', true);
insert into walk_areas (id, name, is_active) values (635, 'Orin', true);
insert into walk_areas (id, name, is_active) values (636, 'Springs', false);
insert into walk_areas (id, name, is_active) values (637, '2nd', true);
insert into walk_areas (id, name, is_active) values (638, 'Hazelcrest', true);
insert into walk_areas (id, name, is_active) values (639, 'Brickson Park', true);
insert into walk_areas (id, name, is_active) values (640, 'Columbus', true);
insert into walk_areas (id, name, is_active) values (641, 'Sugar', true);
insert into walk_areas (id, name, is_active) values (642, 'Anderson', true);
insert into walk_areas (id, name, is_active) values (643, 'Fisk', false);
insert into walk_areas (id, name, is_active) values (644, 'Kings', true);
insert into walk_areas (id, name, is_active) values (645, 'Northridge', false);
insert into walk_areas (id, name, is_active) values (646, 'Portage', true);
insert into walk_areas (id, name, is_active) values (647, 'Crescent Oaks', true);
insert into walk_areas (id, name, is_active) values (648, 'Troy', true);
insert into walk_areas (id, name, is_active) values (649, 'Stoughton', true);
insert into walk_areas (id, name, is_active) values (650, 'Nova', true);
insert into walk_areas (id, name, is_active) values (651, '5th', false);
insert into walk_areas (id, name, is_active) values (652, 'Upham', true);
insert into walk_areas (id, name, is_active) values (653, 'Morrow', true);
insert into walk_areas (id, name, is_active) values (654, 'Dorton', true);
insert into walk_areas (id, name, is_active) values (655, 'Kensington', true);
insert into walk_areas (id, name, is_active) values (656, 'Shasta', false);
insert into walk_areas (id, name, is_active) values (657, 'Forest', true);
insert into walk_areas (id, name, is_active) values (658, 'Homewood', true);
insert into walk_areas (id, name, is_active) values (659, 'Lindbergh', false);
insert into walk_areas (id, name, is_active) values (660, 'Barby', true);
insert into walk_areas (id, name, is_active) values (661, 'Orin', true);
insert into walk_areas (id, name, is_active) values (662, 'Johnson', true);
insert into walk_areas (id, name, is_active) values (663, 'Lien', true);
insert into walk_areas (id, name, is_active) values (664, 'Memorial', true);
insert into walk_areas (id, name, is_active) values (665, 'South', false);
insert into walk_areas (id, name, is_active) values (666, 'Katie', true);
insert into walk_areas (id, name, is_active) values (667, 'Hooker', true);
insert into walk_areas (id, name, is_active) values (668, 'Birchwood', true);
insert into walk_areas (id, name, is_active) values (669, 'Boyd', false);
insert into walk_areas (id, name, is_active) values (670, 'Nova', false);
insert into walk_areas (id, name, is_active) values (671, 'Algoma', false);
insert into walk_areas (id, name, is_active) values (672, 'Fulton', false);
insert into walk_areas (id, name, is_active) values (673, 'Esch', true);
insert into walk_areas (id, name, is_active) values (674, 'Delladonna', true);
insert into walk_areas (id, name, is_active) values (675, 'Karstens', false);
insert into walk_areas (id, name, is_active) values (676, 'Blaine', true);
insert into walk_areas (id, name, is_active) values (677, 'Valley Edge', true);
insert into walk_areas (id, name, is_active) values (678, 'Daystar', true);
insert into walk_areas (id, name, is_active) values (679, 'Meadow Valley', false);
insert into walk_areas (id, name, is_active) values (680, 'New Castle', true);
insert into walk_areas (id, name, is_active) values (681, 'Crownhardt', true);
insert into walk_areas (id, name, is_active) values (682, 'Cordelia', false);
insert into walk_areas (id, name, is_active) values (683, 'Kinsman', true);
insert into walk_areas (id, name, is_active) values (684, 'Meadow Ridge', true);
insert into walk_areas (id, name, is_active) values (685, 'Prairie Rose', true);
insert into walk_areas (id, name, is_active) values (686, '6th', true);
insert into walk_areas (id, name, is_active) values (687, 'Arapahoe', true);
insert into walk_areas (id, name, is_active) values (688, 'Starling', false);
insert into walk_areas (id, name, is_active) values (689, 'Colorado', false);
insert into walk_areas (id, name, is_active) values (690, 'Schmedeman', true);
insert into walk_areas (id, name, is_active) values (691, 'Farragut', true);
insert into walk_areas (id, name, is_active) values (692, 'Lakeland', true);
insert into walk_areas (id, name, is_active) values (693, 'Dwight', true);
insert into walk_areas (id, name, is_active) values (694, 'Becker', true);
insert into walk_areas (id, name, is_active) values (695, 'Eagan', true);
insert into walk_areas (id, name, is_active) values (696, 'Schiller', true);
insert into walk_areas (id, name, is_active) values (697, 'Shopko', true);
insert into walk_areas (id, name, is_active) values (698, 'Truax', true);
insert into walk_areas (id, name, is_active) values (699, 'Browning', true);
insert into walk_areas (id, name, is_active) values (700, 'Blue Bill Park', true);
insert into walk_areas (id, name, is_active) values (701, 'Lerdahl', true);
insert into walk_areas (id, name, is_active) values (702, 'Elgar', true);
insert into walk_areas (id, name, is_active) values (703, 'Grim', false);
insert into walk_areas (id, name, is_active) values (704, 'Memorial', false);
insert into walk_areas (id, name, is_active) values (705, 'Hoard', true);
insert into walk_areas (id, name, is_active) values (706, 'Springview', true);
insert into walk_areas (id, name, is_active) values (707, 'Golf View', true);
insert into walk_areas (id, name, is_active) values (708, 'Tony', true);
insert into walk_areas (id, name, is_active) values (709, 'Graedel', true);
insert into walk_areas (id, name, is_active) values (710, 'Mandrake', true);
insert into walk_areas (id, name, is_active) values (711, 'Karstens', true);
insert into walk_areas (id, name, is_active) values (712, 'Di Loreto', false);
insert into walk_areas (id, name, is_active) values (713, 'Elmside', false);
insert into walk_areas (id, name, is_active) values (714, 'Pennsylvania', false);
insert into walk_areas (id, name, is_active) values (715, 'Sunnyside', true);
insert into walk_areas (id, name, is_active) values (716, 'Village', true);
insert into walk_areas (id, name, is_active) values (717, 'Amoth', true);
insert into walk_areas (id, name, is_active) values (718, 'Vidon', false);
insert into walk_areas (id, name, is_active) values (719, 'Bluestem', true);
insert into walk_areas (id, name, is_active) values (720, 'Schurz', true);
insert into walk_areas (id, name, is_active) values (721, 'Sutteridge', false);
insert into walk_areas (id, name, is_active) values (722, 'Atwood', true);
insert into walk_areas (id, name, is_active) values (723, 'Crowley', true);
insert into walk_areas (id, name, is_active) values (724, 'Towne', true);
insert into walk_areas (id, name, is_active) values (725, 'Fair Oaks', false);
insert into walk_areas (id, name, is_active) values (726, 'Arrowood', false);
insert into walk_areas (id, name, is_active) values (727, 'Memorial', true);
insert into walk_areas (id, name, is_active) values (728, 'Heffernan', false);
insert into walk_areas (id, name, is_active) values (729, 'Northwestern', true);
insert into walk_areas (id, name, is_active) values (730, 'Lawn', false);
insert into walk_areas (id, name, is_active) values (731, 'Grasskamp', false);
insert into walk_areas (id, name, is_active) values (732, 'Bunker Hill', true);
insert into walk_areas (id, name, is_active) values (733, 'Boyd', true);
insert into walk_areas (id, name, is_active) values (734, 'Mayfield', false);
insert into walk_areas (id, name, is_active) values (735, 'Londonderry', true);
insert into walk_areas (id, name, is_active) values (736, 'Cardinal', false);
insert into walk_areas (id, name, is_active) values (737, 'Sachs', true);
insert into walk_areas (id, name, is_active) values (738, 'Westport', false);
insert into walk_areas (id, name, is_active) values (739, 'Rutledge', true);
insert into walk_areas (id, name, is_active) values (740, 'Graceland', false);
insert into walk_areas (id, name, is_active) values (741, 'Talisman', true);
insert into walk_areas (id, name, is_active) values (742, 'Becker', false);
insert into walk_areas (id, name, is_active) values (743, 'Red Cloud', false);
insert into walk_areas (id, name, is_active) values (744, 'Chinook', true);
insert into walk_areas (id, name, is_active) values (745, 'Rigney', true);
insert into walk_areas (id, name, is_active) values (746, 'Pawling', true);
insert into walk_areas (id, name, is_active) values (747, 'Doe Crossing', true);
insert into walk_areas (id, name, is_active) values (748, 'School', true);
insert into walk_areas (id, name, is_active) values (749, '3rd', false);
insert into walk_areas (id, name, is_active) values (750, 'Kinsman', true);
insert into walk_areas (id, name, is_active) values (751, 'Straubel', true);
insert into walk_areas (id, name, is_active) values (752, 'John Wall', true);
insert into walk_areas (id, name, is_active) values (753, 'Dapin', false);
insert into walk_areas (id, name, is_active) values (754, 'Lindbergh', true);
insert into walk_areas (id, name, is_active) values (755, 'Arkansas', true);
insert into walk_areas (id, name, is_active) values (756, 'Golf View', true);
insert into walk_areas (id, name, is_active) values (757, 'Grasskamp', true);
insert into walk_areas (id, name, is_active) values (758, 'Express', true);
insert into walk_areas (id, name, is_active) values (759, 'Canary', true);
insert into walk_areas (id, name, is_active) values (760, 'John Wall', true);
insert into walk_areas (id, name, is_active) values (761, 'Westerfield', true);
insert into walk_areas (id, name, is_active) values (762, 'Northwestern', true);
insert into walk_areas (id, name, is_active) values (763, 'Express', true);
insert into walk_areas (id, name, is_active) values (764, 'Bluejay', true);
insert into walk_areas (id, name, is_active) values (765, 'Pennsylvania', true);
insert into walk_areas (id, name, is_active) values (766, 'Parkside', true);
insert into walk_areas (id, name, is_active) values (767, 'Onsgard', true);
insert into walk_areas (id, name, is_active) values (768, 'Namekagon', true);
insert into walk_areas (id, name, is_active) values (769, 'Southridge', true);
insert into walk_areas (id, name, is_active) values (770, 'Sherman', true);
insert into walk_areas (id, name, is_active) values (771, 'Jay', true);
insert into walk_areas (id, name, is_active) values (772, 'Hansons', true);
insert into walk_areas (id, name, is_active) values (773, 'Emmet', true);
insert into walk_areas (id, name, is_active) values (774, 'Glacier Hill', true);
insert into walk_areas (id, name, is_active) values (775, 'Green', true);
insert into walk_areas (id, name, is_active) values (776, 'Morrow', true);
insert into walk_areas (id, name, is_active) values (777, 'Ramsey', true);
insert into walk_areas (id, name, is_active) values (778, 'Morning', true);
insert into walk_areas (id, name, is_active) values (779, 'Ridgeview', true);
insert into walk_areas (id, name, is_active) values (780, 'Nancy', false);
insert into walk_areas (id, name, is_active) values (781, 'Moland', true);
insert into walk_areas (id, name, is_active) values (782, 'Butternut', false);
insert into walk_areas (id, name, is_active) values (783, 'Cherokee', false);
insert into walk_areas (id, name, is_active) values (784, 'Eastwood', true);
insert into walk_areas (id, name, is_active) values (785, 'Vermont', true);
insert into walk_areas (id, name, is_active) values (786, 'Stephen', true);
insert into walk_areas (id, name, is_active) values (787, 'Porter', true);
insert into walk_areas (id, name, is_active) values (788, 'Longview', true);
insert into walk_areas (id, name, is_active) values (789, 'Golf', true);
insert into walk_areas (id, name, is_active) values (790, 'Fallview', true);
insert into walk_areas (id, name, is_active) values (791, 'Trailsway', true);
insert into walk_areas (id, name, is_active) values (792, 'Moose', true);
insert into walk_areas (id, name, is_active) values (793, 'Daystar', false);
insert into walk_areas (id, name, is_active) values (794, 'Blaine', false);
insert into walk_areas (id, name, is_active) values (795, 'Lake View', false);
insert into walk_areas (id, name, is_active) values (796, 'Canary', true);
insert into walk_areas (id, name, is_active) values (797, 'Ronald Regan', true);
insert into walk_areas (id, name, is_active) values (798, 'Lakeland', true);
insert into walk_areas (id, name, is_active) values (799, 'Barnett', true);
insert into walk_areas (id, name, is_active) values (800, 'Moose', false);
insert into walk_areas (id, name, is_active) values (801, 'Anthes', true);
insert into walk_areas (id, name, is_active) values (802, 'Kennedy', true);
insert into walk_areas (id, name, is_active) values (803, 'Dapin', false);
insert into walk_areas (id, name, is_active) values (804, 'Rockefeller', true);
insert into walk_areas (id, name, is_active) values (805, 'Muir', true);
insert into walk_areas (id, name, is_active) values (806, 'Mendota', true);
insert into walk_areas (id, name, is_active) values (807, 'Sundown', false);
insert into walk_areas (id, name, is_active) values (808, 'Arkansas', false);
insert into walk_areas (id, name, is_active) values (809, 'Randy', true);
insert into walk_areas (id, name, is_active) values (810, 'Grim', true);
insert into walk_areas (id, name, is_active) values (811, 'Cordelia', true);
insert into walk_areas (id, name, is_active) values (812, 'Texas', true);
insert into walk_areas (id, name, is_active) values (813, 'Derek', true);
insert into walk_areas (id, name, is_active) values (814, 'Hauk', true);
insert into walk_areas (id, name, is_active) values (815, 'Del Mar', true);
insert into walk_areas (id, name, is_active) values (816, 'Carberry', false);
insert into walk_areas (id, name, is_active) values (817, 'Bultman', false);
insert into walk_areas (id, name, is_active) values (818, 'Sloan', true);
insert into walk_areas (id, name, is_active) values (819, 'Del Mar', true);
insert into walk_areas (id, name, is_active) values (820, 'Mallard', true);
insert into walk_areas (id, name, is_active) values (821, 'Eggendart', true);
insert into walk_areas (id, name, is_active) values (822, 'Starling', true);
insert into walk_areas (id, name, is_active) values (823, 'David', true);
insert into walk_areas (id, name, is_active) values (824, 'Rowland', true);
insert into walk_areas (id, name, is_active) values (825, 'Lunder', true);
insert into walk_areas (id, name, is_active) values (826, 'North', true);
insert into walk_areas (id, name, is_active) values (827, 'Bartillon', true);
insert into walk_areas (id, name, is_active) values (828, 'Jay', true);
insert into walk_areas (id, name, is_active) values (829, 'Rockefeller', true);
insert into walk_areas (id, name, is_active) values (830, 'Delaware', true);
insert into walk_areas (id, name, is_active) values (831, 'Bluestem', false);
insert into walk_areas (id, name, is_active) values (832, 'Linden', true);
insert into walk_areas (id, name, is_active) values (833, 'Graedel', false);
insert into walk_areas (id, name, is_active) values (834, 'Kropf', true);
insert into walk_areas (id, name, is_active) values (835, 'Elmside', true);
insert into walk_areas (id, name, is_active) values (836, 'Butterfield', true);
insert into walk_areas (id, name, is_active) values (837, 'Oakridge', true);
insert into walk_areas (id, name, is_active) values (838, 'Kings', false);
insert into walk_areas (id, name, is_active) values (839, 'Rockefeller', true);
insert into walk_areas (id, name, is_active) values (840, 'Toban', true);
insert into walk_areas (id, name, is_active) values (841, 'Evergreen', true);
insert into walk_areas (id, name, is_active) values (842, 'Eagle Crest', true);
insert into walk_areas (id, name, is_active) values (843, 'Pepper Wood', true);
insert into walk_areas (id, name, is_active) values (844, 'Cambridge', true);
insert into walk_areas (id, name, is_active) values (845, 'Kinsman', true);
insert into walk_areas (id, name, is_active) values (846, 'Dryden', false);
insert into walk_areas (id, name, is_active) values (847, 'Corry', true);
insert into walk_areas (id, name, is_active) values (848, 'Michigan', false);
insert into walk_areas (id, name, is_active) values (849, 'Park Meadow', false);
insert into walk_areas (id, name, is_active) values (850, 'Manley', true);
insert into walk_areas (id, name, is_active) values (851, 'Hooker', false);
insert into walk_areas (id, name, is_active) values (852, 'Canary', true);
insert into walk_areas (id, name, is_active) values (853, 'Ludington', true);
insert into walk_areas (id, name, is_active) values (854, 'Dahle', false);
insert into walk_areas (id, name, is_active) values (855, 'Cody', true);
insert into walk_areas (id, name, is_active) values (856, 'West', true);
insert into walk_areas (id, name, is_active) values (857, 'Corben', true);
insert into walk_areas (id, name, is_active) values (858, 'Upham', true);
insert into walk_areas (id, name, is_active) values (859, 'Buhler', true);
insert into walk_areas (id, name, is_active) values (860, 'Green', false);
insert into walk_areas (id, name, is_active) values (861, 'Service', true);
insert into walk_areas (id, name, is_active) values (862, 'Vernon', true);
insert into walk_areas (id, name, is_active) values (863, 'Oak Valley', false);
insert into walk_areas (id, name, is_active) values (864, 'Mosinee', true);
insert into walk_areas (id, name, is_active) values (865, 'Scoville', true);
insert into walk_areas (id, name, is_active) values (866, 'Oak', true);
insert into walk_areas (id, name, is_active) values (867, 'Scoville', true);
insert into walk_areas (id, name, is_active) values (868, 'Crownhardt', true);
insert into walk_areas (id, name, is_active) values (869, 'Delladonna', true);
insert into walk_areas (id, name, is_active) values (870, 'Scott', true);
insert into walk_areas (id, name, is_active) values (871, 'Monica', false);
insert into walk_areas (id, name, is_active) values (872, 'International', true);
insert into walk_areas (id, name, is_active) values (873, 'Macpherson', true);
insert into walk_areas (id, name, is_active) values (874, 'Heath', true);
insert into walk_areas (id, name, is_active) values (875, 'Di Loreto', false);
insert into walk_areas (id, name, is_active) values (876, 'Kings', true);
insert into walk_areas (id, name, is_active) values (877, 'Ramsey', true);
insert into walk_areas (id, name, is_active) values (878, 'Dixon', true);
insert into walk_areas (id, name, is_active) values (879, 'Sloan', true);
insert into walk_areas (id, name, is_active) values (880, 'Talisman', true);
insert into walk_areas (id, name, is_active) values (881, 'Ridgeway', true);
insert into walk_areas (id, name, is_active) values (882, 'Gateway', true);
insert into walk_areas (id, name, is_active) values (883, 'Sachtjen', true);
insert into walk_areas (id, name, is_active) values (884, 'Arizona', true);
insert into walk_areas (id, name, is_active) values (885, 'Mosinee', true);
insert into walk_areas (id, name, is_active) values (886, 'Commercial', true);
insert into walk_areas (id, name, is_active) values (887, 'Weeping Birch', true);
insert into walk_areas (id, name, is_active) values (888, 'Maywood', false);
insert into walk_areas (id, name, is_active) values (889, 'Trailsway', true);
insert into walk_areas (id, name, is_active) values (890, 'Sunnyside', true);
insert into walk_areas (id, name, is_active) values (891, 'Lien', false);
insert into walk_areas (id, name, is_active) values (892, 'Esker', true);
insert into walk_areas (id, name, is_active) values (893, 'Havey', true);
insert into walk_areas (id, name, is_active) values (894, 'Erie', true);
insert into walk_areas (id, name, is_active) values (895, 'Jenifer', false);
insert into walk_areas (id, name, is_active) values (896, 'Ramsey', true);
insert into walk_areas (id, name, is_active) values (897, 'Heath', true);
insert into walk_areas (id, name, is_active) values (898, 'Scofield', true);
insert into walk_areas (id, name, is_active) values (899, 'Waywood', true);
insert into walk_areas (id, name, is_active) values (900, 'Swallow', false);
insert into walk_areas (id, name, is_active) values (901, 'Redwing', true);
insert into walk_areas (id, name, is_active) values (902, 'Randy', true);
insert into walk_areas (id, name, is_active) values (903, 'Esch', true);
insert into walk_areas (id, name, is_active) values (904, 'Thierer', true);
insert into walk_areas (id, name, is_active) values (905, 'Mallory', true);
insert into walk_areas (id, name, is_active) values (906, 'Briar Crest', false);
insert into walk_areas (id, name, is_active) values (907, 'Dixon', false);
insert into walk_areas (id, name, is_active) values (908, 'Charing Cross', true);
insert into walk_areas (id, name, is_active) values (909, 'Tennyson', true);
insert into walk_areas (id, name, is_active) values (910, 'East', false);
insert into walk_areas (id, name, is_active) values (911, 'Prairieview', true);
insert into walk_areas (id, name, is_active) values (912, 'Lotheville', true);
insert into walk_areas (id, name, is_active) values (913, 'Leroy', true);
insert into walk_areas (id, name, is_active) values (914, 'Raven', true);
insert into walk_areas (id, name, is_active) values (915, 'Algoma', true);
insert into walk_areas (id, name, is_active) values (916, 'Stone Corner', false);
insert into walk_areas (id, name, is_active) values (917, 'Grayhawk', true);
insert into walk_areas (id, name, is_active) values (918, 'Pond', false);
insert into walk_areas (id, name, is_active) values (919, 'Kipling', false);
insert into walk_areas (id, name, is_active) values (920, 'Old Gate', true);
insert into walk_areas (id, name, is_active) values (921, 'Grover', true);
insert into walk_areas (id, name, is_active) values (922, 'Waywood', true);
insert into walk_areas (id, name, is_active) values (923, 'Cottonwood', true);
insert into walk_areas (id, name, is_active) values (924, 'Petterle', true);
insert into walk_areas (id, name, is_active) values (925, 'Independence', true);
insert into walk_areas (id, name, is_active) values (926, 'Porter', false);
insert into walk_areas (id, name, is_active) values (927, 'Sunbrook', true);
insert into walk_areas (id, name, is_active) values (928, 'Dexter', true);
insert into walk_areas (id, name, is_active) values (929, 'Mariners Cove', true);
insert into walk_areas (id, name, is_active) values (930, 'Scott', true);
insert into walk_areas (id, name, is_active) values (931, 'Redwing', true);
insert into walk_areas (id, name, is_active) values (932, 'Kennedy', true);
insert into walk_areas (id, name, is_active) values (933, 'Delaware', false);
insert into walk_areas (id, name, is_active) values (934, 'Parkside', false);
insert into walk_areas (id, name, is_active) values (935, 'Goodland', true);
insert into walk_areas (id, name, is_active) values (936, 'Lakewood', true);
insert into walk_areas (id, name, is_active) values (937, 'Stang', true);
insert into walk_areas (id, name, is_active) values (938, 'Starling', true);
insert into walk_areas (id, name, is_active) values (939, 'Messerschmidt', true);
insert into walk_areas (id, name, is_active) values (940, 'Morning', true);
insert into walk_areas (id, name, is_active) values (941, 'Michigan', true);
insert into walk_areas (id, name, is_active) values (942, 'Dakota', true);
insert into walk_areas (id, name, is_active) values (943, 'Spaight', true);
insert into walk_areas (id, name, is_active) values (944, 'Pleasure', true);
insert into walk_areas (id, name, is_active) values (945, 'Huxley', false);
insert into walk_areas (id, name, is_active) values (946, 'Grasskamp', true);
insert into walk_areas (id, name, is_active) values (947, 'Prentice', true);
insert into walk_areas (id, name, is_active) values (948, 'Melody', true);
insert into walk_areas (id, name, is_active) values (949, 'Almo', true);
insert into walk_areas (id, name, is_active) values (950, 'Pleasure', true);
insert into walk_areas (id, name, is_active) values (951, 'Waubesa', true);
insert into walk_areas (id, name, is_active) values (952, 'Stuart', true);
insert into walk_areas (id, name, is_active) values (953, 'Schlimgen', false);
insert into walk_areas (id, name, is_active) values (954, 'Briar Crest', true);
insert into walk_areas (id, name, is_active) values (955, 'Myrtle', true);
insert into walk_areas (id, name, is_active) values (956, 'Bobwhite', true);
insert into walk_areas (id, name, is_active) values (957, 'Golf View', true);
insert into walk_areas (id, name, is_active) values (958, 'Karstens', true);
insert into walk_areas (id, name, is_active) values (959, 'Drewry', true);
insert into walk_areas (id, name, is_active) values (960, 'Sheridan', true);
insert into walk_areas (id, name, is_active) values (961, 'Schmedeman', true);
insert into walk_areas (id, name, is_active) values (962, 'Hoepker', true);
insert into walk_areas (id, name, is_active) values (963, 'Annamark', false);
insert into walk_areas (id, name, is_active) values (964, 'High Crossing', true);
insert into walk_areas (id, name, is_active) values (965, 'Moose', true);
insert into walk_areas (id, name, is_active) values (966, 'Haas', true);
insert into walk_areas (id, name, is_active) values (967, 'Corry', true);
insert into walk_areas (id, name, is_active) values (968, 'Sherman', true);
insert into walk_areas (id, name, is_active) values (969, 'Dapin', true);
insert into walk_areas (id, name, is_active) values (970, '8th', true);
insert into walk_areas (id, name, is_active) values (971, 'Ilene', true);
insert into walk_areas (id, name, is_active) values (972, '4th', true);
insert into walk_areas (id, name, is_active) values (973, 'Hauk', true);
insert into walk_areas (id, name, is_active) values (974, 'Banding', true);
insert into walk_areas (id, name, is_active) values (975, 'Eggendart', true);
insert into walk_areas (id, name, is_active) values (976, 'Elka', true);
insert into walk_areas (id, name, is_active) values (977, 'Esch', true);
insert into walk_areas (id, name, is_active) values (978, 'Kingsford', true);
insert into walk_areas (id, name, is_active) values (979, 'Ruskin', true);
insert into walk_areas (id, name, is_active) values (980, 'Karstens', true);
insert into walk_areas (id, name, is_active) values (981, 'Eliot', true);
insert into walk_areas (id, name, is_active) values (982, 'Carpenter', true);
insert into walk_areas (id, name, is_active) values (983, 'Kensington', true);
insert into walk_areas (id, name, is_active) values (984, 'Washington', true);
insert into walk_areas (id, name, is_active) values (985, 'Melby', true);
insert into walk_areas (id, name, is_active) values (986, 'Judy', false);
insert into walk_areas (id, name, is_active) values (987, 'Waubesa', true);
insert into walk_areas (id, name, is_active) values (988, 'Steensland', true);
insert into walk_areas (id, name, is_active) values (989, 'Express', true);
insert into walk_areas (id, name, is_active) values (990, 'Sutherland', true);
insert into walk_areas (id, name, is_active) values (991, 'Novick', true);
insert into walk_areas (id, name, is_active) values (992, 'Doe Crossing', true);
insert into walk_areas (id, name, is_active) values (993, 'Dayton', true);
insert into walk_areas (id, name, is_active) values (994, 'Artisan', true);
insert into walk_areas (id, name, is_active) values (995, 'Waubesa', true);
insert into walk_areas (id, name, is_active) values (996, '4th', true);
insert into walk_areas (id, name, is_active) values (997, 'Schurz', true);
insert into walk_areas (id, name, is_active) values (998, 'Jackson', false);
insert into walk_areas (id, name, is_active) values (999, 'Hagan', true);
insert into walk_areas (id, name, is_active) values (1000, 'Pawling', true);
